theme: dark
run-charts:
  - title: CURL-LATENCY
    data:
      - label: GOOGLE
        script: curl -o /dev/null -s -w '%{time_total}'  http://google.com
      - label: YAHOO
        script: curl -o /dev/null -s -w '%{time_total}'  http://yahoo.com
      - label: YANDEX
        script: curl -o /dev/null -s -w '%{time_total}'  http://yandex.com
    refresh-rate-ms: 200 # TODO consider remove time-scale-sec property, and adjust it automatically based on refresh-rate-ms
    time-scale-sec: 1
    decimal-places: 1
    legend:
      labels: true
      details: true
    position:
      x: 0
      y: 0
    size:
      x: 15
      y: 15
  - title: MONGO-COUNT
    data:
      - label: POSTS
        script: mongo --quiet --host=localhost blog --eval "db.getCollection('post').find({}).size()"
    position:
      x: 15
      y: 0
    size:
      x: 15
      y: 15