runcharts:
- title: SEARCH ENGINE RESPONSE TIME (sec)
  position:
    w: 0
    h: 0
  size:
    w: 40
    h: 18
  scale: 3
  items:
  - label: GOOGLE
    value: curl -o /dev/null -s -w '%{time_total}'  https://www.google.com
  - label: YAHOO
    value: curl -o /dev/null -s -w '%{time_total}'  https://search.yahoo.com
  - label: BING
    value: curl -o /dev/null -s -w '%{time_total}'  https://www.bing.com
- title: SEARCH ENGINE RESPONSE TIME 2 (sec)
  refresh-rate-ms: 5000
  position:
    w: 40
    h: 0
  size:
    w: 20
    h: 18
  legend:
    enabled: true
    details: false
  items:
  - label: GOOGLE
    value: curl -o /dev/null -s -w '%{time_total}'  https://www.google.com
  - label: YAHOO
    value: curl -o /dev/null -s -w '%{time_total}'  https://search.yahoo.com
  - label: BING
    value: curl -o /dev/null -s -w '%{time_total}'  https://www.bing.com
- title: MONGO COLLECTIONS COUNT
  position:
    w: 21
    h: 18
  size:
    w: 19
    h: 13
  scale: 0
  items:
  - label: ACTIVE
    value: mongo --quiet --host=localhost blog --eval "db.getCollection('posts').find({status:'ACTIVE'}).itcount()"
  - label: INACTIVE
    value: mongo --quiet --host=localhost blog --eval "db.getCollection('posts').find({status:'INACTIVE'}).itcount()"
barcharts:
- title: EVENTS BY STATUS
  refresh-rate-ms: 1000
  position:
    w: 0
    h: 18
  size:
    w: 21
    h: 13
  scale: 0
  items:
  - label: NEW
    value: mongo --quiet --host=localhost blog --eval "db.getCollection('posts').find({status:'ACTIVE'}).itcount()"
  - label: TRIGGERED
    value: mongo --quiet --host=localhost blog --eval "db.getCollection('posts').find({status:'INACTIVE'}).itcount()"
  - label: IN_PROCESS
    value: echo 0
  - label: FAILED
    value: mongo --quiet --host=localhost blog --eval "db.getCollection('posts').find({status:'ACTIVE'}).itcount()"
  - label: FINISHED
    value: mongo --quiet --host=localhost blog --eval "db.getCollection('posts').find({status:'INACTIVE'}).itcount()"
gauges:
- title: YEAR PROGRESS
  position:
    w: 21
    h: 33
  size:
    w: 20
    h: 3
  values:
    cur: echo 245
    max: echo 365
    min: echo 0
  items: []
asciiboxes:
- title: LOCAL TIME
  position:
    w: 40
    h: 18
  size:
    w: 20
    h: 6
  value: date +%r
- title: UTC TIME
  position:
    w: 40
    h: 24
  size:
    w: 20
    h: 7
  value: env TZ=UTC date +%r
  font: 3d
