runcharts:
- title: SEARCH ENGINE RESPONSE TIME (sec)
  precision: 3
  position:
    w: 0
    h: 0
  size:
    w: 30
    h: 20
  items:
  - label: GOOGLE
    script: curl -o /dev/null -s -w '%{time_total}'  https://www.google.com
  - label: YAHOO
    script: curl -o /dev/null -s -w '%{time_total}'  https://search.yahoo.com
  - label: YANDEX
    script: curl -o /dev/null -s -w '%{time_total}'  https://yandex.com
  - label: BING
    script: curl -o /dev/null -s -w '%{time_total}'  https://www.bing.com
  - label: DDGO
    script: curl -o /dev/null -s -w '%{time_total}'  https://duckduckgo.com
- title: SEARCH ENGINE RESPONSE TIME 2 (sec)
  refresh-rate-ms: 5000
  position:
    w: 0
    h: 20
  size:
    w: 15
    h: 10
  legend:
    enabled: true
    details: false
  items:
  - label: GOOGLE
    script: curl -o /dev/null -s -w '%{time_total}'  https://www.google.com
  - label: YAHOO
    script: curl -o /dev/null -s -w '%{time_total}'  https://search.yahoo.com
  - label: BING
    script: curl -o /dev/null -s -w '%{time_total}'  https://www.bing.com
- title: MONGO COLLECTIONS COUNT
  position:
    w: 15
    h: 20
  size:
    w: 15
    h: 10
  items:
  - label: POSTS
    script: mongo --quiet --host=localhost blog --eval "db.getCollection('post').find({}).size()"
