runcharts:
- title: SEARCH ENGINE RESPONSE TIME (sec)
  position:
    w: 0
    h: 0
  size:
    w: 53
    h: 22
  scale: 3
  items:
  - label: GOOGLE
    value: curl -o /dev/null -s -w '%{time_total}'  https://www.google.com
  - label: YAHOO
    value: curl -o /dev/null -s -w '%{time_total}'  https://search.yahoo.com
  - label: BING
    value: curl -o /dev/null -s -w '%{time_total}'  https://www.bing.com
- title: SEARCH ENGINE RESPONSE TIME 2 (sec)
  refresh-rate-ms: 5000
  position:
    w: 53
    h: 0
  size:
    w: 27
    h: 22
  legend:
    enabled: true
    details: false
  items:
  - label: GOOGLE
    value: curl -o /dev/null -s -w '%{time_total}'  https://www.google.com
  - label: YAHOO
    value: curl -o /dev/null -s -w '%{time_total}'  https://search.yahoo.com
  - label: BING
    value: curl -o /dev/null -s -w '%{time_total}'  https://www.bing.com
- title: MONGO COLLECTIONS COUNT
  position:
    w: 26
    h: 23
  size:
    w: 27
    h: 17
  scale: 0
  items:
  - label: ACTIVE
    value: mongo --quiet --host=localhost blog --eval "db.getCollection('posts').find({status:'ACTIVE'}).itcount()"
  - label: INACTIVE
    value: mongo --quiet --host=localhost blog --eval "db.getCollection('posts').find({status:'INACTIVE'}).itcount()"
barcharts:
- title: EVENTS BY STATUS
  refresh-rate-ms: 1000
  position:
    w: 0
    h: 23
  size:
    w: 26
    h: 17
  scale: 0
  items:
  - label: NEW
    value: mongo --quiet --host=localhost blog --eval "db.getCollection('posts').find({status:'ACTIVE'}).itcount()"
  - label: TRIGGERED
    value: mongo --quiet --host=localhost blog --eval "db.getCollection('posts').find({status:'INACTIVE'}).itcount()"
  - label: IN_PROCESS
    value: echo 0
  - label: FAILED
    value: mongo --quiet --host=localhost blog --eval "db.getCollection('posts').find({status:'ACTIVE'}).itcount()"
  - label: FINISHED
    value: mongo --quiet --host=localhost blog --eval "db.getCollection('posts').find({status:'INACTIVE'}).itcount()"
gauges:
- title: YEAR PROGRESS
  position:
    w: 0
    h: 41
  size:
    w: 26
    h: 3
  values:
    cur: date +%j
    max: echo 365
    min: echo 0
- title: DAY PROGRESS
  position:
    w: 0
    h: 41
  size:
    w: 26
    h: 3
  values:
    cur: date +%H
    max: echo 24
    min: echo 0
- title: HOUR PROGRESS
  position:
    w: 0
    h: 44
  size:
    w: 26
    h: 3
  values:
    cur: date +%M
    max: echo 60
    min: echo 0
- title: MINUTE PROGRESS
  position:
    w: 0
    h: 47
  size:
    w: 26
    h: 3
  values:
    cur: date +%S
    max: echo 60
    min: echo 0
asciiboxes:
- title: LOCAL TIME
  position:
    w: 53
    h: 23
  size:
    w: 27
    h: 8
  value: date +%r
- title: UTC TIME
  position:
    w: 53
    h: 31
  size:
    w: 27
    h: 9
  value: env TZ=UTC date +%r
  font: 3d
