theme: dark
runcharts:
  - title: SEARCH ENGINE RESPONSE TIME (sec)
    items:
      - label: GOOGLE
        script: curl -o /dev/null -s -w '%{time_total}'  https://www.google.com/
      - label: YAHOO
        script: curl -o /dev/null -s -w '%{time_total}'  https://search.yahoo.com/
      - label: BING
        script: curl -o /dev/null -s -w '%{time_total}'  https://www.bing.com/
    refresh-rate-ms: 200
    decimal-places: 3
    alert:
      value:
        more-than: 0.231
        less-than: 0.123
        equal: 0.144
      indicator:
        terminal: true
        beep: true
    legend:
      enabled: true
      details: true
    position:
      x: 0
      y: 0
    size:
      x: 15
      y: 15
  - title: MONGO COLLECTIONS COUNT
    items:
      - label: POSTS
        script: mongo --quiet --host=localhost blog --eval "db.getCollection('post').find({}).size()"
    position:
      x: 15
      y: 0
    size:
      x: 15
      y: 15
barcharts:
  none
sparklines:
  none
gauges:
  none
lists:
  none
textboxes:
  none
asciiboxes:
  none