theme: dark / bright
line-charts:
  - title: curl-latency
    data:
      - label: example.com
        script: curl -o /dev/null -s -w '%{time_total}'  http://example.com
        color: red
      - label: google.com
        script: curl -o /dev/null -s -w '%{time_total}'  http://google.com
        color: yellow
    refresh-rate-ms: 100
    time-scale-sec: 1
    style: dots/lines
    position:
      x: 1
      y: 2
    size:
      x: 3
      y: 4
  - title: mongo-count
    data:
      - label: posts
        script: mongo --quiet --host=localhost blog --eval "db.getCollection('post').find({}).size()" | grep 2
        color: red
